CodeSchoolServer/Controllers/ArduinoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using CodeSchoolServer.Arduino.Compiler;
using CodeSchoolServer.Data;
using CodeSchoolServer.DTO;
using CodeSchoolServer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CodeSchoolServer.Controllers
{
    public class arduinoBlockModel
    {
        public int projectId { get; set; }
        public string sourceCode { get; set; }
    }


    //[Authorize]
    public class ArduinoController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMapper _mapper;
        private readonly ApplicationDbContext _context;
        private string ProjectFolder = Environment.CurrentDirectory + @"\Arduino\Projects\";
        CompileProcess compileProcess;

        public ArduinoController(SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager,
            ApplicationDbContext applicationDbContext,
            IMapper mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = applicationDbContext;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("FileUpload")]
        public async Task<IActionResult> GetSourceCode(ArduinoModel model)
        {
            CompileProcess compilerProcess = new CompileProcess();

            if (model.SourceFile != null)
            {
                long size = model.SourceFile.Sum(f => f.Length);

                var filePaths = new List<string>();
                foreach (var formFile in model.SourceFile)
                {
                    if (formFile.Length > 0)
                    {
                        // full path to file in temp location
                        var filePath = Path.GetTempFileName(); //we are using Temp file name just for the example. Add your own file path.
                        filePaths.Add(filePath);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            //await formFile.CopyToAsync(stream);
                            compilerProcess.SaveSourceCodeByUser(model.ProjectName, User.Identity.Name, stream);
                        }
                    }
                }
            }
            else
            {
                compilerProcess.SaveSourceCodeByUser(model.ProjectName, User.Identity.Name, null,model.SourceCode);
            }
            

            // process uploaded files
            // Don't rely on or trust the FileName property without validation.

            return View("Index");
        }

        //[HttpPost("FileUpload")]
        //public async Task<IActionResult> FileUpload(List<IFormFile> files)
        //{
        //    long size = files.Sum(f => f.Length);

        //    var filePaths = new List<string>();
        //    foreach (var formFile in files)
        //    {
        //        if (formFile.Length > 0)
        //        {
        //            // full path to file in temp location
        //            var filePath = Path.GetTempFileName(); //we are using Temp file name just for the example. Add your own file path.
        //            filePaths.Add(filePath);

        //            using (var stream = new FileStream(filePath, FileMode.Create))
        //            {
        //                await formFile.CopyToAsync(stream);
        //            }
        //        }
        //    }

        //    // process uploaded files
        //    // Don't rely on or trust the FileName property without validation.

        //    return Ok(new { count = files.Count, size, filePaths });
        //}

        public IActionResult Blocky([FromQuery]string projectId)
        {
            ProjectsDto projectsDto = new ProjectsDto();

            if (Request.Headers.ContainsKey("Authorization"))
            {
                string authValue = Request.Headers["Authorization"].ToString();
                if (authValue != null)
                {
                    byte[] data = Convert.FromBase64String(authValue.Split(null)[1]);
                    string decodedString = Encoding.UTF8.GetString(data);

                    string userEmail = decodedString.Split(':')[0];
                    string password = decodedString.Split(':')[1];

                    var result = _signInManager.PasswordSignInAsync(userEmail, password, false, lockoutOnFailure: false).Result;
                    if (result.Succeeded)
                    {
                        
                        var model = _context.Projects.First(a => a.Id == projectId);
                        projectsDto = _mapper.Map<ProjectsDto>(model);
                        ViewData["ProjectId"] = projectId;
                        getProjectPath(projectsDto);
                        
                        return View();
                    }
                    else
                    {
                        return null;
                    }
                }
            }


            var model2 = _context.Projects.First(a => a.Id == projectId);
            projectsDto = _mapper.Map<ProjectsDto>(model2);
            ViewData["ProjectId"] = projectId;
            getProjectPath(projectsDto);

            return View();

        }

        [HttpPost]
        public void saveProject(string projectId, string xmlCode)
        {
            ProjectsDto projectsDto = new ProjectsDto();
            compileProcess = new CompileProcess();
            var model = _context.Projects.First(a => a.Id == projectId);
            projectsDto = _mapper.Map<ProjectsDto>(model);
            compileProcess.SaveXML(projectsDto, xmlCode);

        }

        [HttpPost]
        public string loadProject(string projectId)
        {
            ProjectsDto projectsDto = new ProjectsDto();
            compileProcess = new CompileProcess();
            var model = _context.Projects.First(a => a.Id == projectId);
            projectsDto = _mapper.Map<ProjectsDto>(model);
            
            return compileProcess.GetXML(projectsDto);
        }
        

        public void saveArduinoCode([FromBody] arduinoBlockModel arduinoBlockModel)
        {

        }

        private Dictionary<string, string> getProjectPath(ProjectsDto projectsDto)
        {
            string projectPath = "";
            Dictionary<string, string> pathSet = new Dictionary<string, string>();
            UnicodeEncoding uniEncoding = new UnicodeEncoding();

            if (projectsDto.ProjectType == 1)//personal
            {
                projectPath = ProjectFolder + @"Users\" + projectsDto.UserId + @"\" + projectsDto.Id + @"\";

                string projectTemplate = projectPath + projectsDto.Id + ".xml";
                pathSet.Add("xmlPath", projectTemplate);
                string projectSourceCode = projectPath + projectsDto.Id + ".ino";
                pathSet.Add("sourceCodePath", projectSourceCode);
                string projectBuildPath = projectPath + projectsDto.Id + @"BuildPath\";
                pathSet.Add("BuildPath", projectBuildPath);
                string projectSourceOut = projectPath + projectsDto.Id + ".bin";
                pathSet.Add("sourceOutPath", projectSourceOut);

                if (!Directory.Exists(projectPath))
                {
                    Directory.CreateDirectory(projectPath);

                    MemoryStream stream;
                    string writeValue = "";
                    using (stream = new MemoryStream())
                    {
                        var sw = new StreamWriter(stream, uniEncoding);
                        var fileStream = new FileStream(projectTemplate, FileMode.Create, FileAccess.Write);
                        try
                        {
                            sw.Write(writeValue);
                            sw.WriteLine();
                            sw.Flush();//otherwise you are risking empty stream
                            stream.Seek(0, SeekOrigin.Begin);

                            // Test and work with the stream here. 
                            // If you need to start back at the beginning, be sure to Seek again.

                            stream.CopyTo(fileStream);
                        }
                        finally
                        {
                            sw.Dispose();
                            fileStream.Dispose();
                        }
                    }
                }


                return pathSet;
            }
            else if (projectsDto.ProjectType == 2)//group
            {
                projectPath = ProjectFolder + @"Groups\" + projectsDto.GroupId + @"\" + projectsDto.UserId + @"\" + projectsDto.Id + @"\";

                string projectTemplate = projectPath + projectsDto.Id + ".xml";
                pathSet.Add("xmlPath", projectTemplate);
                string projectSourceCode = projectPath + projectsDto.Id + ".ino";
                pathSet.Add("sourceCodePath", projectSourceCode);
                string projectBuildPath = projectPath + projectsDto.Id + @"BuildPath\";
                pathSet.Add("BuildPath", projectBuildPath);
                string projectSourceOut = projectPath + projectsDto.Id + ".bin";
                pathSet.Add("sourceOutPath", projectSourceOut);

                if (!Directory.Exists(projectPath))
                {
                    Directory.CreateDirectory(projectPath);

                    MemoryStream stream;
                    string writeValue = "";
                    using (stream = new MemoryStream())
                    {

CodeSchoolServer/Controllers/BlockyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CodeSchoolServer.Controllers
{
    public class BlockyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CodeSchoolServer/Views/Arduino/Blocky - Copy.cshtml
@{
    ViewData["Title"] = "Blocky";
    Layout = "~/Views/Shared/_LayoutBlocky.cshtml";
}

<!-- Horizontal Navigation bar -->
<nav class="nav-fixed arduino_teal">
    <div class="nav-wrapper container">
        <a class="show-on-large button-collapse" href="#" data-activates="slide-out" id="button-collapse"><i class="mdi-navigation-menu"></i></a>
        <a id="logo-container" class="brand-logo">
            <span class="app_title translatable_title">Ardublockly:</span>
            <!-- Sketch name editable text field -->
            <span class="sketch_name_wrapper">
                <i class="mdi-image-edit sketch_name_icon"></i>
                <input id="sketch_name" class="sketch_name" type="text">
            </span>
        </a>
        <!-- Horizontal Navbar links only shown on large resolutions -->
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="#" id="button_load"><span class="translatable_open">Open</span><i class="mdi-file-file-upload left"></i></a></li>
            <li><a href="#" id="button_save"><span class="translatable_save">Save</span><i class="mdi-file-file-download left"></i></a></li>
            <li><a href="#" id="button_delete"><span class="translatable_deleteAll">Delete All</span><i class="mdi-action-delete left"></i></a></li>
        </ul>
    </div>
</nav>

<!-- Sidebar navigation -->
<ul id="slide-out" class="side-nav">
    <li class="logo"><img src="img/sidenav_header.png" alt="Ardublockly block image"></li>
    <li class="no-padding">
        <ul>
            <li id="menu_load"><a href="#"><span class="translatable_open">Open</span><i class="mdi-file-file-upload left"></i></a></li>
            <li id="menu_save"><a href="#"><span class="translatable_save">Save</span><i class="mdi-file-file-download left"></i></a></li>
            <li id="menu_delete"><a href="#"><span class="translatable_deleteAll">Delete All</span><i class="mdi-action-delete left"></i></a></li>
            <li id="menu_settings"><a href="#"><span class="translatable_settings">Settings</span><i class="mdi-action-settings left"></i></a></li>
            <li id="menu_bug"><a href="https://github.com/carlosperate/ardublockly/wiki" target="_blank"><span class="translatable_documentation">Documentation</span><i class="mdi-action-help left"></i></a></li>
            <li id="menu_bug"><a href="http://github.com/carlosperate/ardublockly/issues" target="_blank"><span class="translatable_reportBug">Report Bug</span><i class="mdi-action-bug-report left"></i></a></li>
        </ul>
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li>
                <div class="collapsible-header"><span class="translatable_examples">Examples</span><i class="mdi-navigation-arrow-drop-down"></i></div>
                <div class="collapsible-body">
                    <ul>
                        <li id="menu_example_1"><a href="#!">Blink</a></li>
                        <li id="menu_example_2"><a href="#!">Serial print</a></li>
                        <li id="menu_example_3"><a href="#!">Serial repeat game</a></li>
                        <li id="menu_example_4"><a href="#!">Servo knob</a></li>
                        <li id="menu_example_5"><a href="#!">Stepper knob</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </li>
    <li class="no-padding side-menu-end">&nbsp;</li>
</ul>

<!-- Content -->
<div class="container">
    <div class="row">
        <div class="col s12 m12 l8" style="position:relative">
            <!-- Toolbox visibility button -->
            <a id="button_toggle_toolbox" class="waves-effect waves-light btn-flat button_toggle_toolbox_off" style="display: none"><i id="button_toggle_toolbox_icon" class="mdi-action-visibility-off"></i></a>
            <!-- Arduino IDE action buttons -->
            <div id="ide_buttons_wrapper">
                <a id="button_ide_left" class="waves-effect waves-light waves-circle btn-floating z-depth-1-half arduino_yellow"><i id="button_ide_left_icon" class="mdi-action-open-in-browser"></i></a>
                <a id="button_ide_middle" class="waves-effect waves-light waves-circle btn-floating z-depth-1-half arduino_teal"><i id="button_ide_middle_icon" class="mdi-navigation-check"></i></a>
                <a id="button_ide_large" class="waves-effect waves-light waves-circle btn-floating z-depth-1-half arduino_orange"><i id="button_ide_large_icon" class="mdi-av-play-arrow"></i></a>
                <div id="button_ide_large_spinner" class="preloader-wrapper active ide_loader" style="display:none">
                    <div class="spinner-layer spinner-orange">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div><div class="gap-patch">
                            <div class="circle"></div>
                        </div><div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                    <div class="spinner-layer spinner-dark-teal">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div><div class="gap-patch">
                            <div class="circle"></div>
                        </div><div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                    <div class="spinner-layer spinner-yellow">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div><div class="gap-patch">
                            <div class="circle"></div>
                        </div><div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                    <div class="spinner-layer spinner-light-teal">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div><div class="gap-patch">
                            <div class="circle"></div>
                        </div><div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Blockly Panel -->
            <div class="card-panel white" style="padding: 0">
                <div id="blocks_panel" class="content blocks_panel_large">
                    <div id="content_blocks" class="content z-depth-1"></div>
                </div>
            </div>
        </div>
        <div class="col s12 m12 l4">
            <ul class="collapsible z-depth-1" data-collapsible="accordion">
                <li>
                    <div class="collapsible-header active">
                        <span class="collapsible_logo">{ }</span>
                        <span class="translatable_arduinoSourceCode">Arduino Source Code</span>
                    </div>
                    <div class="collapsible-body">
                        <pre id="content_arduino" class="content content_height_transition content_arduino_large"></pre>
                    </div>
                </li>
                <li>
                    <div class="collapsible-header" id="xml_collapsible_header">
                        <span class="collapsible_logo">&#60; &#62;</span>
                        <span class="translatable_blocksXml">Blocks XML</span>
                    </div>
                    <div class="collapsible-body" style="position:relative" id="xml_collapsible_body">
                        <a class="btn-floating btn-large waves-effect waves-light arduino_teal z-depth-1-half" id="button_load_xml"><i class="mdi-action-extension"></i></a>
                        <textarea id="content_xml" class="content content_height_transition content_xml_large" wrap="soft"></textarea>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<!-- IDE Output content -->
@*<div class="ide_output_wrapper">
    <ul class="collapsible ide_output_collapsible" data-collapsible="expandable">
        <li>
            <div id="ide_output_collapsible_header" class="collapsible-header ide_output_header_normal">
                <i class="mdi-action-swap-vert Medium" style="font-size: 2.2rem;"></i>
                <span class="translatable_arduinoOpMainTitle">Arduino IDE output</span>
            </div>
            <div class="collapsible-body">
                <div id="content_ide_output" class="content"></div>
            </div>
        </li>
    </ul>
</div>*@
<div id="ide_output_spacer"></div>

<!-- Settings: Displayed as a Materialize Modal -->
<div id="settings_dialog" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4><span class="translatable_settings">Settings</span></h4>
        <div class="modal_section">
            <label><span class="translatable_compilerLocation">Compiler Location</span>:</label>
            <input type="text" id="settings_compiler_location">
        </div>
        <div class="modal_section">
            <label><span class="translatable_sketchFolder">Sketch Folder</span>:</label>
            <input type="text" id="settings_sketch_location">
        </div>
        <div class="modal_section">
            <label><span class="translatable_arduinoBoard">Arduino Board</span>:</label>
            <select name="settings_board" id="board">
                <option value="uno" class="translatable_arduinoBoardDefault">Arduino Board unknown</option>
            </select>
        </div>
        <div class="modal_section">
            <label><span class="translatable_comPort">COM Port<span>:</label>
            <select name="settings_serial" id="serial_port">
                <option value="COMX" class="translatable_comPortDefault">COM Port unknown</option>
            </select>
        </div>
        <div class="modal_section">
            <label><span class="translatable_defaultIdeButton">Default IDE button</span>:</label>
            <select name="settings_ide" id="ide_settings">
                <option value="verify" class="translatable_defaultIdeButtonDefault">IDE options unknown</option>
            </select>
        </div>
        <div class="modal_section">
            <label><span class="translatable_language">Language</span>:</label>
            <select name="settings_language" id="language"></select>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" class="waves-effect btn-flat modal-close"><span class="translatable_return">Return</span></a>
    </div>
</div>

<!-- Select Additional Blocks menu -->
<div id="blocks_menu" class="modal modal-fixed-footer">
    <div class="modal-content">
        <div>
            <h4><span class="translatable_addBlocksTitle">Additional Blocks</span></h4>
        </div>
        <div id="blocks_menu_body"></div>
    </div>
    <div class="modal-footer">
        <a href="#" class="waves-effect btn-flat modal-close"><span class="translatable_return">Return</span></a>
    </div>
</div>

<!-- General Alert: Content is loaded using JavaScript to display alerts -->
<div id="gen_alert" class="modal modal_small modal-fixed-footer">
    <div class="modal-content">
        <h5 id="gen_alert_title">
            Empty Alert</h4>
            <p><span id="gen_alert_body">Empty alert text</span></p>
    </div>
    <div class="modal-footer">
        <a id="gen_alert_ok_link" href="#" class="waves-effect btn-flat modal-close"><span class="translatable_okay">Okay</span></a>
        <a id="gen_alert_cancel_link" href="#" class="waves-effect btn-flat modal-close"><span class="translatable_cancel">Cancel</span></a>
    </div>
</div>

<!-- Prompt: Content is loaded using JavaScript to display input prompt -->
<div id="gen_prompt" class="modal modal_small modal-fixed-footer">
    <div class="modal-content">
        <p><span id="gen_prompt_message">Prompt message</span></p>
        <p><input id="gen_prompt_input" value="test" /></p>
    </div>
    <div class="modal-footer">
        <a id="gen_prompt_ok_link" href="#" class="waves-effect btn-flat modal-close"><span class="translatable_okay">Okay</span></a>
        <a id="gen_prompt_cancel_link" href="#" class="waves-effect btn-flat modal-close"><span class="translatable_cancel">Cancel</span></a>
    </div>
</div>

<!-- Local Modal to be shown if Ardublockly Server is not running. -->
@*<div id="not_running_dialog" class="modal">
    <div class="modal-content">
        <div>
            <h4 id="gen_alert_title"><span class="translatable_noServerTitle">Ardublockly app not running</span></h4>
        </div>
        <div class="translatable_noServerBody">
            <p>For all the Ardublockly features to be enabled, the Ardublockly desktop application must be running locally on your computer.</p>
            <p>If you are using an online version you will not be able to configure the settings nor load the blocks code into an Arduino.</p>
            <p>Installation instruction can be found in the <a href="https://github.com/carlosperate/ardublockly">Ardublockly repository</a>.</p>
            <p>If you have Ardublockly already installed, make sure the application is running correctly.</p>
        </div>
    </div>
    <div class="modal-footer">
        <a id="gen_alert_ok_link" href="#" class="waves-effect btn-flat modal-close"><span class="translatable_okay">Okay</span></a>
    </div>
</div>*@

CodeSchoolServer/Views/Arduino/Index.cshtml
@model CodeSchoolServer.Models.ArduinoModel
@using CodeSchoolServer.Enum;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <form asp-controller="Arduino" enctype="multipart/form-data" asp-action="GetSourceCode" asp-route-returnurl="" method="post" role="form">
        <div class="row col-12">
            <div class="form-group col-md-6">
                <label>Project Name: </label>
                <input type="text" asp-for="ProjectName" />
            </div>
            <div class="form-group col-md-6">
                <label>Board Type: </label>
                <select asp-for="BoardType" asp-items="Html.GetEnumSelectList<BoardTypes>()">
                    <option selected="selected" value="">Please select Board</option>
                </select>
            </div>
        </div>
        <div class="row col-12">
            <div class="col-6">
                <div class="form-group">
                    @*<form asp-controller="Arduino" asp-action="GetSourceCode" asp-route-returnurl="" method="post" role="form">*@

                    <textarea asp-for="SourceCode"></textarea>
                    </br>
                    <input name="FormType" type="hidden" value="SourceCode">
                    <button class="btn btn-primary" type="submit">Compile</button>
                    @*</form>*@
                </div>

            </div>
            <div class="col-6">
                @*<form method="post" enctype="multipart/form-data" asp-controller="Arduino" asp-action="FileUpload">*@
                <div class="form-group">
                    <div class="col-md-10">
                        <p>Upload one file using this form:</p>
                        <input type="file" name="SourceFile" asp-for="SourceFile" class="btn btn-outline-info" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Upload" class="btn btn-success" />
                    </div>
                </div>
                @*</form>*@
                <button class="btn btn-success" type="button" onclick="location.href='@Url.Action("blocky")'" >blocky</button>
            </div>
        </div>
    </form>